### ISSUE TITLE
[1pt] Create basic structure for Rockets - Setup

### ISSUE THREAD

**Issue by NitBravoA92** [NitBravoA92/space-travelers-hub#21]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by Kidd254** [comment]
This is the link to the pull request https://github.com/NitBravoA92/space-travelers-hub/pull/29
